[package]
name = "chip-8-interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
pixels = "0.15.0"
rand = "0.9.1"
winit = {version="0.30.11", features=["rwh_05"]}
